### ISSUE TITLE
Resolve JavaScript error on Wallet start

### ISSUE THREAD

**Issue by AK315** [DeStream-dev/Breeze#1]
![img_20181117_175532_622](https://user-images.githubusercontent.com/33836107/48672736-b7e2c700-eb4a-11e8-840d-ea144b6cfbeb.jpg)

**Comment by s-zubov** [comment]
For Windows 7, [SP1 and KB2999226 update ](https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore21) required.
